name: 'Android Emulator Action'
description: 'Starts Android emulator via existing Android SDK installation'
author: 'Malinskiy'
inputs:
  api:
    description: 'api version of the emulator'
    default: '25'
  abi:
    description: 'abi of the emulator'
    default: 'x86'
  tag:
    description: 'default or google_apis'
    default: 'default'
  verbose:
    description: 'be verbose'
    default: 'no'
runs:
  using: 'node12'
  main: 'lib/main.js'
