name: "#22"
on: [push, pull_request]
jobs:
  instrumentationJob:
    name: Run Instrumentation Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test install-sdk
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v12.10.0 && npm install && npm ci && npm run build
        working-directory: install-sdk
      - uses: ./install-sdk
        name: install sdk
      - run: echo "$PATH"
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.6
        with:
          cmd: ./gradlew connectedDebugAndroidTest
          api: 25
          tag: default
          abi: x86
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
