name: "Test simple install workflow"
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: test install-sdk
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v12.10.0 && npm install && npm ci && npm run build
        working-directory: install-sdk
      - uses: ./install-sdk
      - run: adb devices
      - run: echo $ANDROID_HOME
