name: "Test actions in a simple workflow"
on: push
jobs:
  test:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: test install-sdk
      run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v12.10.0 && npm install && npm ci && npm run build
      working-directory: install-sdk
    - name: test emulator-run-cmd
      run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v12.10.0 && npm install && npm ci && npm run build
      working-directory: emulator-run-cmd
    - uses: ./install-sdk
    - uses: ./emulator-run-cmd
      with:
        api: 25
        tag: default
        abi: x86
        cmd: adb shell getprop
