name: "Test action-android/emulator"
on: push
jobs:
  test:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v12.10.0 && npm install && npm ci && npm run build
      working-directory: emulator
    - uses: ./emulator
      with:
        api: 25
        tag: default
        abi: x86
